<Bill>
    MDScreen:
        md_bg_color: self.theme_cls.backgroundColor
    MDBoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            id: topbaraction
            type: "small"
            theme_bg_color: "Custom"
            md_bg_color: hex_color("#ff00aae0")

            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "home"
                    on_release: app.root.current = "main"       
                MDActionTopAppBarButton:
                    icon: "theme-light-dark"
                    on_release: app.switch_theme_style()
                        
            MDTopAppBarTitle:
                text: "PiggyBankExpanseTracker"
                halign: "center"

            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    id: account_button
                    icon: "account-circle-outline"
                    on_release: app.open_account_menu(self)
        AnchorLayout:
            anchor_x: "center"
            anchor_y: "center"

            MDCard:
                size_hint: None, None
                size: "320dp", "420dp"
                padding: "16dp"
                elevation: 2
                style: "elevated"

                MDBoxLayout:
                    orientation: 'vertical'
                    spacing: "15dp"
                    adaptive_height: True
                    pos_hint: {"center_x": .5, "center_y": .5}

                    MDLabel:
                        text: "Add New Bill"
                        style: "headline-small"
                        halign: "center"
                        adaptive_height: True
                        theme_text_color: "Primary"

                    MDTextField:
                        id: bill_amount
                        mode: "outlined"
                        input_filter: "float"
                        MDTextFieldHintText:
                            text: "Add Amount"
                        MDTextFieldLeadingIcon:
                            icon: "currency-usd"

                    MDButton:
                        style: "outlined"
                        pos_hint: {"center_x": .5}
                        on_release: root.open_category_menu(self)
                        MDButtonText:
                            id: drop_item
                            text: "Select Category"
                    
                    MDLabel:
                        id: date_label
                        text: "No Date Selected"
                        halign: "center"
                        style: "body-medium"

                    MDButton:
                        style: "outlined"
                        pos_hint: {"center_x": .5}
                        on_release: root.show_date_picker()
                        MDButtonText:
                            text: "Pick Due Date"

                    MDButton:
                        style: "filled"
                        pos_hint: {"center_x": .5}
                        on_release: root.save_expense()
                        MDButtonText:
                            text: "Save Expense"
                    
                    MDButton:
                        style: "text"
                        pos_hint: {"center_x": .5}
                        on_release: app.root.current = "main"
                        MDButtonText:
                            text: "Cancel"                   