#: import hex_color kivy.utils.get_color_from_hex
<MainScreen>:
    MDNavigationLayout:
        ScreenManager:
            MDScreen:
                md_bg_color: self.theme_cls.backgroundColor

                BoxLayout:
                    orientation: 'vertical'
                    

                    MDTopAppBar:
                        id: topbaraction
                        type: "small"
                        theme_bg_color: "Custom"
                        md_bg_color:hex_color("#ff00aae0")
                        MDTopAppBarLeadingButtonContainer:
                            MDActionTopAppBarButton:
                                icon: "menu"
                               
                            MDActionTopAppBarButton:
                                icon: "theme-light-dark"
                                on_release: app.switch_theme_style()
                        
                        MDTopAppBarTitle:
                            text: "PiggyBankExpanseTracker"
                            halign: "center"

                        MDTopAppBarTrailingButtonContainer:
                            MDActionTopAppBarButton:
                                id: account_button
                                icon: "account-circle-outline"
                                on_release: app.open_account_menu(self)
                    BoxLayout:
                        orientation:'vertical'
                        spacing:10
                        padding:50
                        pos_hint: {'center_x': 0.5,'center_y': 0.5}
                        MDCard:
                            size_hint_x: None
                            size: 400,200
                            pos_hint: {'center_x': 0.5,'center_y': 0.5}
                            MDLabel:
                                id:balance_label
                                text:"test_balance"
                                halign:"center"
                        MDCard:
                            size_hint_x: None
                            size: 400,200
                            pos_hint: {'center_x': 0.5,'center_y': 0.5}
                            MDLabel:
                                id: total_label
                                size_hint_x: None
                                text:"test_total"
                                halign:"center"
                    AnchorLayout:
                        anchor_x: "center"
                        anchor_y: "center" 
                        GridLayout:
                            cols:4
                            rows:1
                            spacing:30
                            padding:20
                            size_hint: None, None
                            size: 520,200
                            MDButton:
                                style: "filled"
                                on_press: app.root.current = 'addfund'
                                MDButtonText:
                                    id:add_fund
                                    text: "Add fund"
                        
                            MDButton:
                                id: add_bill
                                style: "filled"
                                on_press:app.root.current ="bill"
                                MDButtonText:
                                    text: "Add bill"
                            MDButton:
                                id: add_target
                                style: "filled"
                                on_release: app.root.current = "target"
                                MDButtonText:
                                    text: "Add Target"
                            MDButton:
                                id: overview
                                style: "filled"

                                MDButtonText:
                                    text: "Savenigs Overview"    
                        MDButton:
                            style: "tonal"
                            on_release: app.root.current = "target"
                            MDButtonText:
                                text: "View All Savings Goals"                     