#:import hex_color kivy.utils.get_color_from_hex

<Saveingsview>:
    MDBoxLayout:
        orientation: 'vertical'
        md_bg_color: self.theme_cls.backgroundColor

        MDTopAppBar:
            id: topbaraction
            type: "small"
            theme_bg_color: "Custom"
            md_bg_color: hex_color("#ff00aae0")

            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "home"
                    on_release: app.root.current = "main"       
                MDActionTopAppBarButton:
                    icon: "theme-light-dark"
                    on_release: app.switch_theme_style()
                        
            MDTopAppBarTitle:
                text: "PiggyBankExpanseTracker"
                halign: "center"

            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    id: account_button
                    icon: "account-circle-outline"
                    on_release: app.open_account_menu(self)


        MDScrollView:
            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True
                padding: "16dp"
                spacing: "20dp"

                MDCard:
                    orientation: "vertical"
                    padding: "16dp"
                    size_hint_y: None
                    height: "180dp"
                    style: "filled"
                    theme_bg_color: "Custom"
                    md_bg_color: self.theme_cls.primaryContainerColor

                    MDLabel:
                        text: "Spending Overview"
                        style: "title-medium"
                    
                    MDBoxLayout:
                        MDLabel:
                            text: "Total Income"
                            style: "body-small"
                        MDLabel:
                            id: total_income_label
                            text: "$0.00"
                            halign: "right"
                            style: "title-small"

                    MDBoxLayout:
                        MDLabel:
                            text: "Total Expenses"
                            style: "body-small"
                        MDLabel:
                            id: total_expense_label
                            text: "$0.00"
                            halign: "right"
                            style: "title-small"
                            theme_text_color: "Error"

                    MDLabel:
                        text: "Budget Used"
                        style: "label-small"
                    
                    MDLinearProgressIndicator:
                        id: spending_progress
                        value: 0
                        height: "4dp"

                MDLabel:
                    text: "Transaction History"
                    style: "title-medium"
                    adaptive_height: True

                MDList:
                    id: history_list